### ISSUE TITLE
Understanding the knapsackBB_hybrid.cpp code

### ISSUE THREAD

**Issue by sid-1207** [TuitaTeam/Knapsack-Hybrid#1]
Hey, if this is still active, is there an explanation for this code and how things work?

**Comment by sanchezfauste** [comment]
Hi! This is the documentation of the project: [Knapsack-Hybrid.pdf](https://github.com/TuitaTeam/Knapsack-Hybrid/files/8662680/Knapsack-Hybrid.pdf)
